---

- name: Copy kubeconfig to local machine
  fetch:
    dest: /Users/{{ ansible_user_id }}/.kube/
    src: /home/{{ ansible_user }}/.kube/config

- name: Install Helm
  shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh

- name: Add Longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Launch Longhorn helm chart on cluster
  kubernetes.core.helm:
    name: longhorn
    release_namespace: longhorn-system
    create_namespace: true
    chart_ref: longhorn/longhorn
    chart_version: 1.3.0

- name: Wait for all Longhorn pods become created
  shell: "kubectl get po --namespace=longhorn-system --output=jsonpath='{.items[*].metadata.name}'"
  register: control_plane_pods_created
  until: item in control_plane_pods_created.stdout
  retries: 10
  delay: 30
  with_items:
    - longhorn-ui
    - longhorn-driver-deployer
    - longhorn-conversion-webhook
    - csi-snapshotter
    - csi-resizer
    - csi-provisioner
    - csi-attacher
  tags:
    - wait


- name: Wait for control-plane pods become ready
  shell: "kubectl wait --namespace=longhorn-system --for=condition=Ready pods --all --timeout=600s"
  register: control_plane_pods_ready
  tags:
    - wait

- debug: var=control_plane_pods_ready.stdout_lines
  tags:
    - wait
