apiVersion: v1
kind: Service
metadata:
  name:  longhoun-ui-lb
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort: 8000